plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: "Blog - Austin Weisgrau"
tagline: "Explorations in data and software development."
email: austinweisgrau@gmail.com
author: Austin Weisgrau
url: "http://aradox66.github.io"
baseurl: "/"

collections:
  categories:
    output: true

defaults:
  - scope:
      path: ''
      type: 'categories'
    values:
      layout: 'default'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'default'
  - scope:
      path: ''
    values:
      layout: 'default'